In [1]:
import numpy as np

# Для создания матрицы с заданными значениями
# используется функция `np.array()`, как и для векторов,
# но, в отличие от векторов, матрицы могут быть многомерными

A = np.array([[1, 2], [3, 4], [5, 6]])  # матрица размера 3x2
print(A)

# Output:
# [[1 2]
# [3 4]
# [5 6]]


[[1 2]
 [3 4]
 [5 6]]


In [2]:
O = np.zeros(shape=(3, 2))
print(O)

# Output:
# [[0. 0.]
# [0. 0.]
# [0. 0.]]


[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [3]:
E = np.ones(shape=(3, 2))
print(E)

# Output:
# [[1. 1.]
# [1. 1.]
# [1. 1.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
rng = np.random.default_rng()
R = rng.random(size=(3, 2))
print(R)

# Output:
# [[0.47821453 0.28421059]
# [0.2178972  0.07891322]
# [0.63259903 0.4502506 ]]


[[0.58945909 0.3213902 ]
 [0.3040799  0.51073564]
 [0.908642   0.07486613]]


In [8]:
print(A[0, 1])
print(A[1:3])
print(A[0:2, 0])

# Output:
# 2
# array([[3, 4],
#       [5, 6]])
# array([1, 3])


2
[[3 4]
 [5 6]]
[1 3]


In [9]:
import pandas as pd

# Создаём матрицу в виде списка списков
A = [
    [1, 2],
    [3, 4],
    [5, 6]
]

# Преобразуем список списков в DataFrame и задаём имена столбцов
df = pd.DataFrame(A, columns=["Column1", "Column2"])

# Выводим DataFrame (матрицу)
print(df)

# Output:
#     Column1  Column2
#  0        1        2
#  1        3        4
#  2        5        6


   Column1  Column2
0        1        2
1        3        4
2        5        6


In [10]:
import pandas as pd

# Группировка и агрегация данных по категориальному признаку
# Допустим, у нас есть данные о зарплатах по отделам
data_group = {
    'Отдел': ['HR', 'IT', 'HR', 'IT', 'HR'],
    'Зарплата': [40000, 70000, 45000, 72000, 42000]
}
df_group = pd.DataFrame(data_group)
# Группируем по столбцу 'Отдел' и 
# вычисляем среднюю зарплату в каждом отделе
grouped = df_group.groupby('Отдел').mean()
print("Средняя зарплата по отделам:")
print(grouped)

# Output:
# Средняя зарплата по отделам:
#            Зарплата
# Отдел              
# HR     42333.333333
# IT     71000.000000


Средняя зарплата по отделам:
           Зарплата
Отдел              
HR     42333.333333
IT     71000.000000


In [11]:
import numpy as np
from scipy.sparse import coo_matrix

# Определяем ненулевые элементы: их значения и позиции (строки и столбцы)
rows = np.array([0, 1, 2, 0])
cols = np.array([1, 2, 0, 2])
data = np.array([10, 20, 30, 40])

# Создаём матрицу размером 3x3
sparse_coo = coo_matrix((data, (rows, cols)), shape=(3, 3))

print("Исходная матрица:")
print(sparse_coo.toarray())

print("\nРазрежённая матрица в формате COO:")
print(sparse_coo)

# Output:
# Исходная матрица:
# [[ 0 10 40]
#  [ 0  0 20]
#  [30  0  0]]
 
# Разрежённая матрица в формате COO:
#   (0, 1)	10
#   (1, 2)	20
#   (2, 0)	30
#   (0, 2)	40


Исходная матрица:
[[ 0 10 40]
 [ 0  0 20]
 [30  0  0]]

Разрежённая матрица в формате COO:
<COOrdinate sparse matrix of dtype 'int64'
	with 4 stored elements and shape (3, 3)>
  Coords	Values
  (0, 1)	10
  (1, 2)	20
  (2, 0)	30
  (0, 2)	40


In [12]:
import numpy as np
import pandas as pd
from scipy.sparse import coo_matrix

# Шаг 1: Создаём базовый NumPy array
data = np.array([[0, 0, 3],
                 [4, 0, 0],
                 [0, 5, 6]])
print("Исходный NumPy array:")
print(data)

# Шаг 2: Преобразуем NumPy array в разрежённую матрицу в формате COO
sparse_matrix = coo_matrix(data)
print("\nРазрежённая матрица (COO формат):")
print(sparse_matrix)

# Шаг 3: Преобразуем разрежённую матрицу обратно в плотный NumPy array
dense_array = sparse_matrix.toarray()
print("\nПлотный NumPy array, полученный из разрежённой матрицы:")
print(dense_array)

# Шаг 4: Создаём DataFrame Pandas на основе плотного массива
df = pd.DataFrame(dense_array, columns=['Column1', 'Column2', 'Column3'])
print("\nDataFrame (Pandas):")
print(df)

# Output:
# Исходный NumPy array:
# [[0 0 3]
#  [4 0 0]
#  [0 5 6]]

# Разрежённая матрица (COO формат):
#   (0, 2)	3
#   (1, 0)	4
#   (2, 1)	5
#   (2, 2)	6

# Плотный NumPy array, полученный из разрежённой матрицы:
# [[0 0 3]
#  [4 0 0]
#  [0 5 6]]

# DataFrame (Pandas):
#    Column1  Column2  Column3
# 0        0        0        3
# 1        4        0        0
# 2        0        5        6


Исходный NumPy array:
[[0 0 3]
 [4 0 0]
 [0 5 6]]

Разрежённая матрица (COO формат):
<COOrdinate sparse matrix of dtype 'int64'
	with 4 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	3
  (1, 0)	4
  (2, 1)	5
  (2, 2)	6

Плотный NumPy array, полученный из разрежённой матрицы:
[[0 0 3]
 [4 0 0]
 [0 5 6]]

DataFrame (Pandas):
   Column1  Column2  Column3
0        0        0        3
1        4        0        0
2        0        5        6
